name: Flask CI/CD Pipeline

on:
  push:
    branches:
      - staging

jobs:

  build-and-test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          source venv/bin/activate
          pytest -v

      - name: Build Docker Image
        run: |
          docker build -t akash0505/flask-practice:latest .

      - name: Save Docker Image
        run: |
          docker save akash0505/flask-practice:latest -o flask-image.tar

      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flask-image
          path: flask-image.tar

   deploy:

    needs: build-and-test

    runs-on: ubuntu-latest

    steps:

      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v4
        with:
          name: flask-image

      - name: Load Docker Image
        run: |
          docker load -i flask-image.tar

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker push akash0505/flask-practice:latest
